import {
  BackpackIcon,
  CameraIcon,
  Crosshair1Icon,
  DownloadIcon,
  HamburgerMenuIcon,
  ImageIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  LayersIcon,
  MixerHorizontalIcon,
  PauseIcon,
  PersonIcon,
  ReloadIcon,
  PlayIcon,
  StopIcon,
  UploadIcon,
  SymbolIcon,
  ViewVerticalIcon,
} from "@radix-ui/react-icons";

export const Icons = {
  library: BackpackIcon,
  inspector: MixerHorizontalIcon,
  layers: LayersIcon,
  timeline: ViewVerticalIcon,
  puppet: PersonIcon,
  decor: ImageIcon,
  asset: SymbolIcon,
  pause: PauseIcon,
  play: PlayIcon,
  stop: StopIcon,
  fit: Crosshair1Icon,
  save: DownloadIcon,
  open: UploadIcon,
  menu: HamburgerMenuIcon,
  camera: CameraIcon,
  zoomIn: MagnifyingGlassPlusIcon,
  zoomOut: MagnifyingGlassMinusIcon,
  zoomReset: ReloadIcon,
};
