import {
  BackpackIcon,
  CameraIcon,
  Crosshair1Icon,
  DownloadIcon,
  HamburgerMenuIcon,
  ImageIcon,
  MinusIcon,
  PlusIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  LayersIcon,
  MixerHorizontalIcon,
  PauseIcon,
  PersonIcon,
  ReloadIcon,
  PlayIcon,
  StopIcon,
  UploadIcon,
  SymbolIcon,
  ViewVerticalIcon,
  QuestionMarkCircledIcon,
} from "@radix-ui/react-icons";

export const Icons = {
  library: BackpackIcon,
  inspector: MixerHorizontalIcon,
  layers: LayersIcon,
  timeline: ViewVerticalIcon,
  puppet: PersonIcon,
  decor: ImageIcon,
  asset: SymbolIcon,
  pause: PauseIcon,
  play: PlayIcon,
  stop: StopIcon,
  fit: Crosshair1Icon,
  save: DownloadIcon,
  open: UploadIcon,
  menu: HamburgerMenuIcon,
  camera: CameraIcon,
  zoomIn: PlusIcon,
  zoomOut: MinusIcon,
  zoomReset: ReloadIcon,
  prevKeyframe: DoubleArrowLeftIcon,
  nextKeyframe: DoubleArrowRightIcon,
  help: QuestionMarkCircledIcon,
};
